package com.formaplus.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import com.formaplus.utils.LoadView;

import javafx.event.ActionEvent;

public class LoginController {
	@FXML
	private TextField txtLogin;
	@FXML
	private TextField txtMdp;
	@FXML
	private Button btnLogin;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void btnLoginAction(ActionEvent event) {
		// TODO Autogenerated
		LoadView.showView("Main", "Main");
		
	}
}
