package com.formaplus.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import com.formaplus.dao.models.Utilisateur;
import com.formaplus.dao.repositories.RepositoryFactory;
import com.formaplus.utils.AlertMessage;
import com.formaplus.utils.LoadView;

import at.favre.lib.crypto.bcrypt.BCrypt;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginController {
	@FXML
	private TextField loginField;
	@FXML
	private PasswordField passwordField;
	@FXML
	private Button loginButton;

	// Event Listener on Button[#loginButton].onAction
	@FXML
	public void handeLoginButtonAction(ActionEvent event) {
		// TODO Autogenerated
		if(!loginField.getText().isEmpty() || !passwordField.getText().isEmpty()) {
			
			Utilisateur u = RepositoryFactory.getUtilisateurRepository().login(loginField.getText());
			if(u != null) {
				BCrypt.Result result = BCrypt.verifyer().verify(passwordField.getText().toCharArray(), u.getMdpUtr());
				if(result.verified) LoadView.showView("Main", "Main");
				else AlertMessage.showInformation("Informations de connexion incorrecte");
			} else AlertMessage.showInformation("Informations de connexion incorrecte");
			
		} else AlertMessage.showInformation("Informations de connexion incorrecte");
		
	}
}
