package com.formaplus.controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import com.formaplus.dao.models.Etudiant;
import com.formaplus.dao.models.Formation;
import com.formaplus.dao.models.Paiement;
import com.formaplus.dao.repositories.RepositoryFactory;
import com.formaplus.utils.LoadView;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class PaiementsController implements Initializable {
	@FXML
	private BorderPane borderPane;
	@FXML
	private AnchorPane mainAnchorePane;
	@FXML
	private TableView<Paiement> payTable;
	@FXML
	private TableColumn<Paiement, Integer> idPay;
	@FXML
	private TableColumn<Paiement, Etudiant> etudiantColumn;
	@FXML
	private TableColumn<Paiement, Formation> formationColumn;
	@FXML
	private TableColumn<Paiement, Double> montantPay;
	@FXML
	private TableColumn<Paiement, String> datePay;
	@FXML
	private Button editButton;
	@FXML
	private Button deleteButton;
	@FXML
	private Button printButton;
	@FXML
	private Button addButton;
	
	private ObservableList<Paiement> payListe;
	
	
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		etudiantColumn.setCellValueFactory(cellData -> cellData.getValue().etudiantProperty());
		montantPay.setCellValueFactory(cellData -> cellData.getValue().montantPayProperty().asObject());
		datePay.setCellValueFactory(new PropertyValueFactory<Paiement, String>("datePay"));
		this.formationColumn.setCellValueFactory(cellData -> cellData.getValue().inscriptionProperty().get().formationProperty());
		this.loadPay();
		
	}
	
	private void loadPay() {
		this.payListe = RepositoryFactory.getPaiementRepository().getAll();
		this.payTable.setItems(this.payListe);
	}
	

	// Event Listener on Button[#editButton].onAction
	@FXML
	public void handleEditButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#deleteButton].onAction
	@FXML
	public void handleDeleteButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#printButton].onAction
	@FXML
	public void handlePrintButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addButton].onAction
	@FXML
	public void handleAddButtonAction(ActionEvent event) {
		Stage dialogStage = LoadView.getModalStage(addButton, "AddPaiement", "Enrégistrer un paiement");
		dialogStage.setOnCloseRequest(evt -> loadPay());
		dialogStage.showAndWait();
	}
	
}
